Math Magicians components and ui
gracekabaghe/math-magicians pull request #3
Opened 2021-11-30 17:34 UTC by gracekabaghe

- Created a directory called components.
- Inside components, created a new Calculator.js file.
- In Calculator.js, created a React component that matches this design:

2021-11-30 18:07 UTC, rloterh requested changes
Hi Grace, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- Descriptive Pull Request
- No linter errors

## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 18:07 UTC, rloterh commented on src/App.js
>  function App() {
- [x] Kindly ensure that the _main_(App) component is a **stateful/ class-based** component, as specified.

2021-11-30 18:07 UTC, rloterh commented on src/components/Calculator.js
> +const Calculator = () => (
- [x] Kindly ensure that the _Calulator_ component is a **stateful/ class-based** component, as specified.

2021-11-30 19:30 UTC, dasileker requested changes
## **Hi @gracekabaghe,** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 19:30 UTC, dasileker commented on src/components/Calculator.js
> +        <button type="button" className="button highlight">&divide;</button>
- [ ] As my colleague said the Calculator.js should be a class-based app.

![mmm](https://user-images.githubusercontent.com/61562626/144114474-134f8a49-c3ea-4629-8534-8f833af43b9d.jpeg)

2021-11-30 19:30 UTC, dasileker commented on src/App.js
> -    <div className="App">
- [ ] the same goes for the App.js file.


![ooo](https://user-images.githubusercontent.com/61562626/144114653-532bebf9-08ec-4960-a391-04554cb81594.jpeg)

2021-12-02 08:13 UTC, ArthurGC approved these changes
# Approved project!  💯 ✅ 🥳 🎈 🎉
Hi  @gracekabaghe 

Amazing job implementing suggestions from the previous reviewer! 💯 
Your project is complete! :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/3o7buh8WbaZLupolXi/giphy.gif)

## Aspects to improve ♻️
- [OPTIONAL] It would be better to add a customized README instead of README that comes from React by default. A good start would be the [MICROVERSE README](https://github.com/microverseinc/readme-template)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-02 08:33 UTC, merged